In [2]:
import pandas as pd

In [3]:
a = {'students' : ['david','samuel','terry','evan'],'age':['27','24','22','32'],
     'country':['uk','canada','chine','usa'],
     'course':['python','data structure','machine learning','web development'],
    'marks':['85','72','89','76']}

In [4]:
df = pd.DataFrame(a)

In [5]:
b=df[['marks']]
b

  marks
0    85
1    72
2    89
3    76

In [6]:
c=df[['country','course']]
c

  country            course
0      uk            python
1  canada    data structure
2   chine  machine learning
3     usa   web development

In [7]:
df[['students']]

  students
0    david
1   samuel
2    terry
3     evan

loc[row_lable,column_lable], iloc[row_index, column_index]
slicing loc[row,column] u can use index and coumn name or lable both in single brace "[]" using "loc" or "iloc" function

Day 2

In [8]:
%pip install xlrd openpyxl

Requirement already satisfied: xlrd in c:\users\prati\appdata\local\programs\python\python311\lib\site-packages (2.0.2)
Requirement already satisfied: openpyxl in c:\users\prati\appdata\local\programs\python\python311\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\prati\appdata\local\programs\python\python311\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/LXjSAttmoxJfEG6il1Bqfw/Product-sales.csv"
df = pd.read_csv(filename)

In [10]:
df.head()

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
0,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
1,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
2,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
3,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
4,5,Monitor,Electronics,1,300,300,2022-05-21,Miami

In [12]:
q=df[['Price']]
q

   Price
0    800
1    600
2    150
3      2
4    300

In [14]:
q=df[["Product","Category"]]
q

      Product     Category
0      Laptop  Electronics
1  Smartphone  Electronics
2  Desk Chair    Furniture
3    Notebook   Stationery
4     Monitor  Electronics

In [16]:
df.iloc[1,2]

'Electronics'

In [18]:
new_index=['a','b','c','d','e']
df_new = df
df_new.index = new_index
df_new.loc['a','CustomerCity']
df_new.loc['a':'b','CustomerCity']

a       New York
b    Los Angeles
Name: CustomerCity, dtype: str