In [2]:
import pandas as pd

In [3]:
a = {'students' : ['david','samuel','terry','evan'],'age':['27','24','22','32'],
     'country':['uk','canada','chine','usa'],
     'course':['python','data structure','machine learning','web development'],
    'marks':['85','72','89','76']}

In [4]:
df = pd.DataFrame(a)

In [5]:
b=df[['marks']]
b

  marks
0    85
1    72
2    89
3    76

In [6]:
c=df[['country','course']]
c

  country            course
0      uk            python
1  canada    data structure
2   chine  machine learning
3     usa   web development

In [11]:
df[['students']]

  students
0    david
1   samuel
2    terry
3     evan

loc[row_lable,column_lable], iloc[row_index, column_index]
slicing loc[row,column] u can use index and coumn name or lable both in single brace "[]" using "loc" or "iloc" function